---
- name: Set interpreter (Default 2.7.x)
  set_fact:
    ansible_python_interpreter=/usr/bin/python

- name: Install GUI
  become: yes
  yum: name="epel-release.noarch" state=present

- name: Update /etc/yum.conf
  become: yes
  shell: sh -c 'echo group_package_types=default,mandatory >> /etc/yum.conf'

- name: Install X Window system
  become: yes
  yum: name="@X Window system" enablerepo=epel state=present

- name: Install MATE-Desktop
  become: yes
  yum: name="@MATE-Desktop" enablerepo=epel state=present

- name: Japanese font
  become: yes
  yum: name="vlgothic-*" state=present

- name: Append .xinitrc
  blockinfile:
    #dest: /$HOME/.xinitrc
    dest: "{{ userhome }}/.xinitrc"
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK FOR MATE-SESSION -->"
    create: yes
    block: |
      exec mate-session

- name: Set default
  become: yes
  shell: systemctl set-default graphical.target

- name: Install fcitx(instead of iBus for Pycharm warning.)
  become: yes
  yum: name={{ item }} enablerepo="epel" state=present
  with_items:
  - fcitx-data.noarch
  - fcitx-devel.x86_64
  - fcitx-gtk2.x86_64
  - fcitx-gtk3.x86_64
  - fcitx-libs.x86_64
  - fcitx-pinyin.x86_64
  - fcitx-qw.x86_64
  - fcitx-table.x86_64
  - fcitx-anthy.x86_64
  - fcitx.x86_64
  - fcitx-configtool.x86_64

- name: blockinfile
  blockinfile:
    dest: "{{ userhome }}/.bash_profile"
    create: yes
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK FOR FCITX SETTINGS -->"
    block: |
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS="@im=fcitx"
      export LANG=ja_JP.UTF-8

- name: Japanize
  become: yes
  shell: localectl set-locale LANG=ja_JP.UTF-8

- name: Create terminal color profile(dconf).
  become: yes
  blockinfile:
    dest: "/tmp/mate-terminal-dconf.txt"
    create: yes
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK FOR MATE-TERMINAL SETTINGS -->"
    block: |
      [profiles/default]
      foreground-color='#E6E6E6E6E6E6'
      visible-name='Default'
      palette='#EEEEEEEEECEC'
      title='Terminal'
      background-darkness=0.82999999999999996
      use-system-font=false
      use-theme-colors=false
      background-type='solid'
      font='VL Gothic Bold 10'
      allow-bold=true
      bold-color='#FFFFFFFFFFFF'
      background-color='#404000000000'
      title-mode='ignore'

- name: set terminal color profile.
  shell: "dbus-launch dconf load /org/mate/terminal/ < /tmp/mate-terminal-dconf.txt"

- name: Put Pycharm web site on Desktop
  blockinfile:
    create: yes
    path: "{{ userhome }}/Desktop/GetPycharm.desktop"
    block: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=GetPyCharm
      Type=Link
      URL=https://www.jetbrains.com/pycharm/
      Icon=/usr/share/icons/hicolor/16x16/apps/firefox.png


#- name: Change folder names in English expression.
#  shell: 'echo "LANG=C xdg-user-dirs-gtk-update" > ~/デスクトップ/Change-folder-names-English.sh'
#  ignore_errors: yes


