---
- name: Install nginx
  become: yes
  yum: name=nginx state=present

- name: Make nginx log directory
  become: yes
  file:
    path=/var/log/nginx
    state=directory 
    owner=root 
    group=root 
    mode=0755

- name: Add and enable nginx service
  become: yes
  service: name=nginx enabled=yes state=started
 
