---

- name: Install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Download pyenv
  git:
    repo=git://github.com/pyenv/pyenv.git
    dest=/home/vagrant/.pyenv
    accept_hostkey=yes

- name: Edit bash_profile
  blockinfile:
    dest: /home/vagrant/.bash_profile
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- name: Set interpreter
  set_fact: 
    ansible_python_interpreter=/home/vagrant/.pyenv/shims/python

- name: Exec pyenv versions
  shell: bash -lc "pyenv versions | grep {{ python_ver }}"
  register: result_v1
  ignore_errors: yes
  changed_when: False

- name: Install python interpreter.
  shell: bash -lc "pyenv install {{ python_ver }}"
  when: result_v1 is failed

- name: Set global python version.
  shell: bash -lc "pyenv global {{ python_ver }}"
  when: result_v1 is failed

- name: Upgrade pip
  shell: pip install --upgrade pip
  register: result
  #changed_when: '”already up-to-date” not in result.stdout'

- name: Upgrade setuptools
  shell: pip install --upgrade setuptools
  register: result
  #changed_when: '”already up-to-date” not in result.stdout'

