---

- name: Install the 'Development tools' package group
  become: yes
  yum: name="@Development tools" state=present

- name: Install dependencies
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - readline-devel
    - zlib-devel
    - bzip2-devel
    - sqlite-devel
    - openssl-devel
    - libXext.x86_64
    - libSM.x86_64
    - libXrender.x86_64
    - libffi-devel
    - python-devel
    - tk.x86_64
    - tk-devel.x86_64
    - tkinter.x86_64

- name: Download pyenv
  git:
    repo=https://github.com/pyenv/pyenv.git
    dest="{{ userhome }}/.pyenv"
    accept_hostkey=yes

- name: Edit bash_profile
  blockinfile:
    dest: "{{ userhome }}/.bash_profile"
    block: |
      export PYENV_ROOT="{{ userhome }}/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi

- name: Reload bash_profile
  shell: "source {{ userhome }}/.bash_profile"

- name: Exec pyenv versions
  shell: bash -lc "pyenv versions | grep {{ python_ver }}"
  ignore_errors: yes
  changed_when: False

- name: pyenv versions
  shell: bash -lc "pyenv versions"
  ignore_errors: yes

- name: Install python interpreter.
  shell: bash -lc "pyenv install {{ python_ver }}"
  #shell: "pyenv install {{ python_ver }}"
  ignore_errors: yes

- name: Set global python version.
  shell: bash -lc "pyenv global {{ python_ver }}"
  ignore_errors: yes

- name: Set shell python version.
  shell: bash -lc "pyenv shell {{ python_ver }}"
  ignore_errors: yes

- name: Set interpreter
  set_fact: 
    ansible_python_interpreter="{{ userhome }}/.pyenv/versions/{{ python_ver }}/bin/python"

- name: Upgrade pip
  shell: "{{ userhome }}/.pyenv/versions/{{ python_ver }}/bin/pip install --upgrade pip"
  register: result
  #changed_when: '”already up-to-date” not in result.stdout'

- name: Upgrade setuptools
  shell: "{{ userhome }}/.pyenv/versions/{{ python_ver }}/bin/pip install --upgrade setuptools"
  register: result
  #changed_when: '”already up-to-date” not in result.stdout'

- name: Set interpreter (Default 2.7.x)
  set_fact: 
    ansible_python_interpreter=/usr/bin/python

