---
- name: update yum
  become: yes
  get_url:
    url=https://yum.puppetlabs.com/RPM-GPG-KEY-puppet
    dest=/tmp/RPM-GPG-KEY-puppet

- name: Add gpg key for centos7 yum update operation.
  rpm_key:
    state: present
    key: https://yum.puppetlabs.com/RPM-GPG-KEY-puppet
validate_certs: yes

- name: Ensure the yum package index is up to Date
  yum:
    update_cache: yes
    name: '*'
    state: latest

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Add epel-release repository.
  yum:
    name: epel-release
    state: latest

- name: Preparing for installing Guest Additions.
  yum:
    name={{ item }} state=latest
  with_items:
    - bzip2 
    - gcc 
    - gcc-c++ 
    - make 
    - perl 
    - kernel-devel


- name: Install utility softwares.
  yum:
    name={{ item }} state=latest
  with_items:
    - vim
    - tcpflow

